Attribute VB_Name = "Módulo_Global"
Option Explicit

Global CAMPO(1 To 82) As Object
Global USUARIO As String
Global EDITARUSUARIO As Boolean

'MACRO UTILIZADA PARA ATRIBUIR NÚMERO AOS CAMPOS DO FORMULÁRIO'
Sub ATRIBUIRCAMPOS()

Set CAMPO(1) = UserFormSISTEMA.TextBoxMUNICIPIO
Set CAMPO(2) = UserFormSISTEMA.TextBoxNUCLEO
Set CAMPO(3) = UserFormSISTEMA.TextBoxENTREVISTADOR
Set CAMPO(4) = UserFormSISTEMA.TextBoxQUADRA
Set CAMPO(5) = UserFormSISTEMA.TextBoxLOTE
Set CAMPO(6) = UserFormSISTEMA.TextBoxDOMICILIO
Set CAMPO(7) = UserFormSISTEMA.TextBoxENDERECO
Set CAMPO(8) = UserFormSISTEMA.TextBoxNº
Set CAMPO(9) = UserFormSISTEMA.TextBoxCOMPLEMENTO
Set CAMPO(10) = UserFormSISTEMA.TextBoxTELEFONE
Set CAMPO(11) = UserFormSISTEMA.TextBox1VISITA
Set CAMPO(12) = UserFormSISTEMA.ComboBox1VISITA
Set CAMPO(13) = UserFormSISTEMA.TextBox2VISITA
Set CAMPO(14) = UserFormSISTEMA.ComboBox2VISITA
Set CAMPO(15) = UserFormSISTEMA.TextBox3VISITA
Set CAMPO(16) = UserFormSISTEMA.ComboBox3VISITA
Set CAMPO(17) = UserFormSISTEMA.TextBoxEDIFICACOES
Set CAMPO(18) = UserFormSISTEMA.ComboBoxUSODOIMOVEL
Set CAMPO(19) = UserFormSISTEMA.ComboBoxOCUPACAODOIMOVEL
Set CAMPO(20) = UserFormSISTEMA.TextBoxOUTROOCUPACAO
Set CAMPO(21) = UserFormSISTEMA.TextBoxTEMPOMORADIA
Set CAMPO(22) = UserFormSISTEMA.ComboBoxRENDA
'CAMPOS 1º RESPONSÁVEL 1'
Set CAMPO(23) = UserFormSISTEMA.TextBoxNOME1
Set CAMPO(24) = UserFormSISTEMA.TextBoxNOMEDOPAI1
Set CAMPO(25) = UserFormSISTEMA.TextBoxNOMEDAMAE1
Set CAMPO(26) = UserFormSISTEMA.ComboBoxSEXO1
Set CAMPO(27) = UserFormSISTEMA.TextBoxNASC1
Set CAMPO(28) = UserFormSISTEMA.TextBoxNACIONALIDADE1
Set CAMPO(29) = UserFormSISTEMA.ComboBoxNAT1
Set CAMPO(30) = UserFormSISTEMA.TextBoxRG1
Set CAMPO(31) = UserFormSISTEMA.TextBoxORGAOEXP1
Set CAMPO(32) = UserFormSISTEMA.TextBoxCPF1
Set CAMPO(33) = UserFormSISTEMA.TextBoxPROFISSAO1
Set CAMPO(34) = UserFormSISTEMA.ComboBoxESTCIVIL1
Set CAMPO(35) = UserFormSISTEMA.TextBoxCASAMENTO1
Set CAMPO(36) = UserFormSISTEMA.ComboBoxREGIME1
Set CAMPO(37) = UserFormSISTEMA.ComboBoxESTADODEFATO1
Set CAMPO(38) = UserFormSISTEMA.ComboBoxP1_1
Set CAMPO(39) = UserFormSISTEMA.ComboBoxP1_2
Set CAMPO(40) = UserFormSISTEMA.ComboBoxP1_3
Set CAMPO(41) = UserFormSISTEMA.ComboBoxP1_4
Set CAMPO(42) = UserFormSISTEMA.ComboBoxP1_5
'CAMPOS 2º RESPONSÁVEL'
Set CAMPO(43) = UserFormSISTEMA.TextBoxNOME2
Set CAMPO(44) = UserFormSISTEMA.TextBoxNOMEDOPAI2
Set CAMPO(45) = UserFormSISTEMA.TextBoxNOMEDAMAE2
Set CAMPO(46) = UserFormSISTEMA.ComboBoxSEXO2
Set CAMPO(47) = UserFormSISTEMA.TextBoxNASC2
Set CAMPO(48) = UserFormSISTEMA.TextBoxNACIONALIDADE2
Set CAMPO(49) = UserFormSISTEMA.ComboBoxNAT2
Set CAMPO(50) = UserFormSISTEMA.TextBoxRG2
Set CAMPO(51) = UserFormSISTEMA.TextBoxORGAOEXP2
Set CAMPO(52) = UserFormSISTEMA.TextBoxCPF2
Set CAMPO(53) = UserFormSISTEMA.TextBoxPROFISSAO2
Set CAMPO(54) = UserFormSISTEMA.ComboBoxESTCIVIL2
Set CAMPO(55) = UserFormSISTEMA.TextBoxCASAMENTO2
Set CAMPO(56) = UserFormSISTEMA.ComboBoxREGIME2
Set CAMPO(57) = UserFormSISTEMA.ComboBoxESTADODEFATO2
Set CAMPO(58) = UserFormSISTEMA.ComboBoxP2_1
Set CAMPO(59) = UserFormSISTEMA.ComboBoxP2_2
Set CAMPO(60) = UserFormSISTEMA.ComboBoxP2_3
Set CAMPO(61) = UserFormSISTEMA.ComboBoxP2_4
Set CAMPO(62) = UserFormSISTEMA.ComboBoxP2_5
'CAMPOS CÓPIAS RECOLHIDAS E OBSERVAÇÕES'
Set CAMPO(63) = UserFormSISTEMA.ComboBoxCRG1
Set CAMPO(64) = UserFormSISTEMA.ComboBoxCCPF1
Set CAMPO(65) = UserFormSISTEMA.ComboBoxCNASC1
Set CAMPO(66) = UserFormSISTEMA.ComboBoxCCAS1
Set CAMPO(67) = UserFormSISTEMA.TextBoxCOUTRO1
Set CAMPO(68) = UserFormSISTEMA.ComboBoxCRG2
Set CAMPO(69) = UserFormSISTEMA.ComboBoxCCPF2
Set CAMPO(70) = UserFormSISTEMA.ComboBoxCNASC2
Set CAMPO(71) = UserFormSISTEMA.ComboBoxCCAS2
Set CAMPO(72) = UserFormSISTEMA.TextBoxCOUTRO2
Set CAMPO(73) = UserFormSISTEMA.ComboBoxCONTRATOVC
Set CAMPO(74) = UserFormSISTEMA.ComboBoxCOMPROMISSOVC
Set CAMPO(75) = UserFormSISTEMA.ComboBoxCESSAODIREITOS
Set CAMPO(76) = UserFormSISTEMA.ComboBoxRECIBOS
Set CAMPO(77) = UserFormSISTEMA.ComboBoxCDOACAO
Set CAMPO(78) = UserFormSISTEMA.ComboBoxCLOCACAO
Set CAMPO(79) = UserFormSISTEMA.ComboBoxCCOMODATO
Set CAMPO(80) = UserFormSISTEMA.TextBoxCOUTRO
Set CAMPO(81) = UserFormSISTEMA.TextBoxOBS

End Sub

Sub PREENCHERCADASTROS()

Dim RS As New ADODB.Recordset
Dim SQL As String
Dim CAMPOS2(1 To 81) As String
Dim CAMPOSFINAL As String
Dim I As Integer
Dim TODASCOLUNAS As String

TODASCOLUNAS = "MUNICÍPIO,NÚCLEO,ENTREVISTADOR,QUADRA,LOTE,DOMICÍLIO,ENDEREÇO," _
& "Nº,COMPLEMENTO,TELEFONE,[1ª VISITA],[1ª VISITA - SITUAÇÃO],[2ª VISITA],[2ª VISITA - SITUAÇÃO]," _
& "[3ª VISITA],[3ª VISITA - SITUAÇÃO],[Nº EDIFICAÇÕES],[USO DO IMÓVEL],[OCUPAÇÃO DO IMÓVEL],OUTRO," _
& "[TEMPO DE MORADIA],[RENDA FAMILIAR],[1º RESPONSÁVEL - NOME],[1º RESPONSÁVEL - NOME DO PAI]," _
& "[1º RESPONSÁVEL - NOME DA MÃE],[1º RESPONSÁVEL - SEXO],[1º RESPONSÁVEL - DATA NASC]," _
& "[1º RESPONSÁVEL - NACIONALIDADE],[1º RESPONSÁVEL - NATURALIDADE-UF],[1º RESPONSÁVEL - RG/RNE]," _
& "[1º RESPONSÁVEL - ORGÃO EXPEDIDOR/UF],[1º RESPONSÁVEL - CPF],[1º RESPONSÁVEL - PROFISSÃO]," _
& "[1º RESPONSÁVEL - ESTADO CIVIL],[1º RESPONSÁVEL - DATA DO CASAMENTO],[1º RESPONSÁVEL - REGIME DE BENS]," _
& "[1º RESPONSÁVEL - ESTADO DE FATO],[1º RESPONSÁVEL - P1],[1º RESPONSÁVEL - P2],[1º RESPONSÁVEL - P3]," _
& "[1º RESPONSÁVEL - P4], [1º RESPONSÁVEL - P5],[2º RESPONSÁVEL - NOME],[2º RESPONSÁVEL - NOME DO PAI]," _
& "[2º RESPONSÁVEL - NOME DA MÃE],[2º RESPONSÁVEL - SEXO],[2º RESPONSÁVEL - DATA NASC]," _
& "[2º RESPONSÁVEL - NACIONALIDADE],[2º RESPONSÁVEL - NATURALIDADE-UF],[2º RESPONSÁVEL - RG/RNE]," _
& "[2º RESPONSÁVEL - ORGÃO EXPEDIDOR/UF],[2º RESPONSÁVEL - CPF],[2º RESPONSÁVEL - PROFISSÃO]," _
& "[2º RESPONSÁVEL - ESTADO CIVIL],[2º RESPONSÁVEL - DATA DO CASAMENTO],[2º RESPONSÁVEL - REGIME DE BENS]," _
& "[2º RESPONSÁVEL - ESTADO DE FATO],[2º RESPONSÁVEL - P1],[2º RESPONSÁVEL - P2],[2º RESPONSÁVEL - P3]," _
& "[2º RESPONSÁVEL - P4], [2º RESPONSÁVEL - P5],[CÓPIA 1º RESPONSÁVEL - RG],[CÓPIA 1º RESPONSÁVEL - CPF]," _
& "[CÓPIA 1º RESPONSÁVEL - CERT NASC],[CÓPIA 1º RESPONSÁVEL - CERT CASAMENTO / ÓBITO],[CÓPIA 1º RESPONSÁVEL - OUTRO]," _
& "[CÓPIA 2º RESPONSÁVEL - RG],[CÓPIA 2º RESPONSÁVEL - CPF],[CÓPIA 2º RESPONSÁVEL - CERT NASC]," _
& "[CÓPIA 2º RESPONSÁVEL - CERT CASAMENTO / ÓBITO],[CÓPIA 2º RESPONSÁVEL - OUTRO],[CONTRATO DE VENDA E COMPRA]," _
& "[COMPROMISSO DE VENDA E COMPRA],[CONTRATO DE CESSÃO DE DIREITOS],[RECIBOS DE COMPRA],[CONTRATO DE DOAÇÃO]," _
& "[CONTRATO DE LOCAÇÃO],[CONTRATO DE COMODATO],[OUTRO DOC IMÓVEL],OBSERVAÇÕES"

    For I = 1 To 81
        CAMPOS2(I) = "'" & CAMPO(I) & "'"
    Next

    For I = 1 To 81
        CAMPOSFINAL = CAMPOSFINAL & CAMPOS2(I)
            If I < 81 Then CAMPOSFINAL = CAMPOSFINAL & ","
    Next

If UserFormSISTEMA.LBMODO.Caption = "EDITAR" Then
    Call EDITARREGISTROS(UserFormSISTEMA.LBID.Caption, TODASCOLUNAS, CAMPOS2())
    Exit Sub
End If

SQL = "INSERT INTO CADASTROS(MUNICÍPIO,NÚCLEO,ENTREVISTADOR,QUADRA,LOTE,DOMICÍLIO,ENDEREÇO," _
& "Nº,COMPLEMENTO,TELEFONE,[1ª VISITA],[1ª VISITA - SITUAÇÃO],[2ª VISITA],[2ª VISITA - SITUAÇÃO]," _
& "[3ª VISITA],[3ª VISITA - SITUAÇÃO],[Nº EDIFICAÇÕES],[USO DO IMÓVEL],[OCUPAÇÃO DO IMÓVEL],OUTRO," _
& "[TEMPO DE MORADIA],[RENDA FAMILIAR],[1º RESPONSÁVEL - NOME],[1º RESPONSÁVEL - NOME DO PAI]," _
& "[1º RESPONSÁVEL - NOME DA MÃE],[1º RESPONSÁVEL - SEXO],[1º RESPONSÁVEL - DATA NASC]," _
& "[1º RESPONSÁVEL - NACIONALIDADE],[1º RESPONSÁVEL - NATURALIDADE-UF],[1º RESPONSÁVEL - RG/RNE]," _
& "[1º RESPONSÁVEL - ORGÃO EXPEDIDOR/UF],[1º RESPONSÁVEL - CPF],[1º RESPONSÁVEL - PROFISSÃO]," _
& "[1º RESPONSÁVEL - ESTADO CIVIL],[1º RESPONSÁVEL - DATA DO CASAMENTO],[1º RESPONSÁVEL - REGIME DE BENS]," _
& "[1º RESPONSÁVEL - ESTADO DE FATO],[1º RESPONSÁVEL - P1],[1º RESPONSÁVEL - P2],[1º RESPONSÁVEL - P3]," _
& "[1º RESPONSÁVEL - P4], [1º RESPONSÁVEL - P5],[2º RESPONSÁVEL - NOME],[2º RESPONSÁVEL - NOME DO PAI]," _
& "[2º RESPONSÁVEL - NOME DA MÃE],[2º RESPONSÁVEL - SEXO],[2º RESPONSÁVEL - DATA NASC]," _
& "[2º RESPONSÁVEL - NACIONALIDADE],[2º RESPONSÁVEL - NATURALIDADE-UF],[2º RESPONSÁVEL - RG/RNE]," _
& "[2º RESPONSÁVEL - ORGÃO EXPEDIDOR/UF],[2º RESPONSÁVEL - CPF],[2º RESPONSÁVEL - PROFISSÃO]," _
& "[2º RESPONSÁVEL - ESTADO CIVIL],[2º RESPONSÁVEL - DATA DO CASAMENTO],[2º RESPONSÁVEL - REGIME DE BENS]," _
& "[2º RESPONSÁVEL - ESTADO DE FATO],[2º RESPONSÁVEL - P1],[2º RESPONSÁVEL - P2],[2º RESPONSÁVEL - P3]," _
& "[2º RESPONSÁVEL - P4], [2º RESPONSÁVEL - P5],[CÓPIA 1º RESPONSÁVEL - RG],[CÓPIA 1º RESPONSÁVEL - CPF]," _
& "[CÓPIA 1º RESPONSÁVEL - CERT NASC],[CÓPIA 1º RESPONSÁVEL - CERT CASAMENTO / ÓBITO],[CÓPIA 1º RESPONSÁVEL - OUTRO]," _
& "[CÓPIA 2º RESPONSÁVEL - RG],[CÓPIA 2º RESPONSÁVEL - CPF],[CÓPIA 2º RESPONSÁVEL - CERT NASC]," _
& "[CÓPIA 2º RESPONSÁVEL - CERT CASAMENTO / ÓBITO],[CÓPIA 2º RESPONSÁVEL - OUTRO],[CONTRATO DE VENDA E COMPRA]," _
& "[COMPROMISSO DE VENDA E COMPRA],[CONTRATO DE CESSÃO DE DIREITOS],[RECIBOS DE COMPRA],[CONTRATO DE DOAÇÃO]," _
& "[CONTRATO DE LOCAÇÃO],[CONTRATO DE COMODATO],[OUTRO DOC IMÓVEL],OBSERVAÇÕES) "

SQL = SQL & "VALUES(" & CAMPOSFINAL & ")"

RS.Open SQL, BD

MsgBox "CADASTRO SALVO COM SUCESSO", vbInformation, "INFORMAÇÃO"

End Sub

Sub EDITARREGISTROS(ID As Long, TODASCOLUNAS As String, REGISTRO() As String)

Dim SQL As String
Dim COLUNA() As String
Dim I As Integer
Dim STRINGFINAL As String
Dim RS As New ADODB.Recordset

COLUNA = Split(TODASCOLUNAS, ",")

For I = 1 To 81
    STRINGFINAL = STRINGFINAL & COLUNA(I - 1) & "=" & REGISTRO(I)
    If I < 81 Then STRINGFINAL = STRINGFINAL & ","
Next

STRINGFINAL = "SET " & STRINGFINAL
SQL = "Update CADASTROS " & STRINGFINAL
SQL = SQL & " WHERE ID LIKE " & ID

RS.Open SQL, BD

MsgBox "CADASTRO EDITADO COM SUCESSO!", vbInformation, "INFORMAÇÃO"

End Sub

Sub DELETAR()

Dim ID As Double
Dim SQL As String
Dim RS As New ADODB.Recordset

ID = UserFormSISTEMA.LBID.Caption

SQL = "DELETE FROM CADASTROS WHERE ID LIKE " & ID
RS.Open SQL, BD


MsgBox "O CADASTRO FOI DELETADO COM SUCESSO!", vbInformation, "INFORMAÇÃO"

End Sub

Sub CARREGARCOMBOBOX()

'CAMPO SEXO'
UserFormSISTEMA.ComboBoxSEXO1.AddItem "FEMININO"
UserFormSISTEMA.ComboBoxSEXO1.AddItem "MASCULINO"
UserFormSISTEMA.ComboBoxSEXO2.AddItem "FEMININO"
UserFormSISTEMA.ComboBoxSEXO2.AddItem "MASCULINO"

'CAMPOS PERGUNTAS P1'
UserFormSISTEMA.ComboBoxP1_1.AddItem "SIM"
UserFormSISTEMA.ComboBoxP1_1.AddItem "NÃO"
UserFormSISTEMA.ComboBoxP1_2.AddItem "SIM"
UserFormSISTEMA.ComboBoxP1_2.AddItem "NÃO"
UserFormSISTEMA.ComboBoxP1_3.AddItem "SIM"
UserFormSISTEMA.ComboBoxP1_3.AddItem "NÃO"
UserFormSISTEMA.ComboBoxP1_4.AddItem "SIM"
UserFormSISTEMA.ComboBoxP1_4.AddItem "NÃO"
UserFormSISTEMA.ComboBoxP1_5.AddItem "SIM"
UserFormSISTEMA.ComboBoxP1_5.AddItem "NÃO"

'CAMPOS PERGUNTAS P2'
UserFormSISTEMA.ComboBoxP2_1.AddItem "SIM"
UserFormSISTEMA.ComboBoxP2_1.AddItem "NÃO"
UserFormSISTEMA.ComboBoxP2_2.AddItem "SIM"
UserFormSISTEMA.ComboBoxP2_2.AddItem "NÃO"
UserFormSISTEMA.ComboBoxP2_3.AddItem "SIM"
UserFormSISTEMA.ComboBoxP2_3.AddItem "NÃO"
UserFormSISTEMA.ComboBoxP2_4.AddItem "SIM"
UserFormSISTEMA.ComboBoxP2_4.AddItem "NÃO"
UserFormSISTEMA.ComboBoxP2_5.AddItem "SIM"
UserFormSISTEMA.ComboBoxP2_5.AddItem "NÃO"

'CAMPOS CÓPIAS RECOLHIDAS'
UserFormSISTEMA.ComboBoxCRG1.AddItem "OK"
UserFormSISTEMA.ComboBoxCCPF1.AddItem "OK"
UserFormSISTEMA.ComboBoxCNASC1.AddItem "OK"
UserFormSISTEMA.ComboBoxCCAS1.AddItem "OK"

UserFormSISTEMA.ComboBoxCRG2.AddItem "OK"
UserFormSISTEMA.ComboBoxCCPF2.AddItem "OK"
UserFormSISTEMA.ComboBoxCNASC2.AddItem "OK"
UserFormSISTEMA.ComboBoxCCAS2.AddItem "OK"

UserFormSISTEMA.ComboBoxCONTRATOVC.AddItem "OK"
UserFormSISTEMA.ComboBoxCOMPROMISSOVC.AddItem "OK"
UserFormSISTEMA.ComboBoxCESSAODIREITOS.AddItem "OK"
UserFormSISTEMA.ComboBoxRECIBOS.AddItem "OK"
UserFormSISTEMA.ComboBoxCDOACAO.AddItem "OK"
UserFormSISTEMA.ComboBoxCLOCACAO.AddItem "OK"
UserFormSISTEMA.ComboBoxCCOMODATO.AddItem "OK"

End Sub

Sub DELETARUSUARIO(NOMEUSUARIO As String)

Dim SQL As String
Dim RS As New ADODB.Recordset

SQL = "DELETE FROM USUARIO WHERE USUÁRIO LIKE " & "'" & NOMEUSUARIO & "'"

RS.Open SQL, BD

MsgBox "USUÁRIO DELETADO COM SUCESSO!", vbInformation, "INFORMAÇÃO"

End Sub

Sub FILTROAVANÇADO()

Dim RS As New ADODB.Recordset
Dim SQL As String
Dim I As Long
Dim BASEREGISTRO As Range
On Error Resume Next
Dim NUCLEO As String
Dim QUADRA As String
Dim LOTE As String
Dim DOMICILIO As String
Dim ENTREVISTADOR As String
Dim CONTROLES(1 To 5) As Object
Dim VALORES(1 To 5) As String

Set CONTROLES(1) = UserFormSISTEMA.TextBoxFILTRONUCLEO
Set CONTROLES(2) = UserFormSISTEMA.TextBoxFILTROQUADRA
Set CONTROLES(3) = UserFormSISTEMA.TextBoxFILTROLOTE
Set CONTROLES(4) = UserFormSISTEMA.TextBoxFILTRODOMICILIO
Set CONTROLES(5) = UserFormSISTEMA.TextBoxFILTROENTREVISTADOR

For I = 1 To 5
    If CONTROLES(I) = "" Then
        VALORES(I) = "'%'"
        Else
        VALORES(I) = "'" & CONTROLES(I).Value & "%'"
    End If
Next


NUCLEO = "'" & UserFormSISTEMA.TextBoxFILTRONUCLEO.Value & "'"
QUADRA = "'" & UserFormSISTEMA.TextBoxFILTROQUADRA.Value & "'"
LOTE = "'" & UserFormSISTEMA.TextBoxFILTROLOTE.Value & "'"
DOMICILIO = "'" & UserFormSISTEMA.TextBoxFILTRODOMICILIO.Value & "'"
ENTREVISTADOR = "'" & UserFormSISTEMA.TextBoxFILTROENTREVISTADOR.Value & "'"

SQL = "SELECT ID,NÚCLEO,QUADRA,LOTE,DOMICÍLIO,ENTREVISTADOR FROM CADASTROS "
SQL = SQL & " WHERE NÚCLEO LIKE " & VALORES(1)
SQL = SQL & " AND QUADRA LIKE " & VALORES(2)
SQL = SQL & " AND LOTE LIKE " & VALORES(3)
SQL = SQL & " AND DOMICÍLIO LIKE " & VALORES(4)
SQL = SQL & " AND ENTREVISTADOR LIKE " & VALORES(5)
SQL = SQL & " ORDER BY ID"

RS.Open SQL, BD

'LIMPAR A PLANILHA'
BASE.Range("A1").CurrentRegion.Offset(1, 0).ClearContents
BASE.Range("A2").CopyFromRecordset RS
I = BASE.Range("A1").CurrentRegion.Rows.Count

    If I > 1 Then
        Set BASEREGISTRO = BASE.Range(BASE.Cells(2, 1), BASE.Cells(I, 6))
    Else
        Set BASEREGISTRO = BASE.Range(BASE.Cells(2, 1), BASE.Cells(2, 6))
    End If
UserFormSISTEMA.LISTAREGISTROS.RowSource = BASEREGISTRO.Address(, , , True)
RS.Close

End Sub
